using UnityEngine;
public enum AchievementIds
{
    // Fields
    NUNU_FOUND = 0
    ,OCTOPIA_SAVED = 1
    ,POWER_TYPES_USED = 2
    ,PEARL_FARMER_10000 = 3
    ,PEARL_TYCOON_20000 = 4
    ,PEARL_GATHRER_5000 = 5
    ,OCTASTICT = 6
    ,LORD_OF_THE_TENTACLES = 7
    ,OCEAN_CRUISE_5 = 8
    ,LOST_AT_SEA_20 = 9
    ,MARINE_EXPEDITION_10 = 10
    ,UNINTERRUPTED_SQUIRTING = 11
    ,SPENDER_1 = 12
    ,BIG_SPENDER_10 = 13
    ,SCUBA_DIVER_25 = 14
    ,EXPERT_DIVER_50 = 15
    ,MASTER_DIVER_100 = 16
    ,YOU_REALLY_CRACK_ME_UP = 17
    ,MASTER_CEPHALOPOD = 18
    ,SWIMMING_ON_THE_EDGE = 19
    ,YOU_SERIOUSLY_CRACK_ME_UP = 20
    ,PERFECTIONIST = 21
    ,NOW_IT_IS_OVER = 22
    ,IKA_COLLECTOR = 23
    ,TAKO_COLLECTOR = 24
    ,YOU_CRACK_ME_UP = 25
    ,THEY_ARE_FINISHED = 26
    ,SPECIES_OBSERVER = 27
    ,TENTACLE_CONFRONTATION = 28
    ,TENTACLE_WARFARE = 29
    ,TENTACLE_ARMAGEDDON = 30
    ,BEACHCOMBER = 31
    ,LARVA_WARRIOR = 32
    ,TENTACLE_WARRIOR = 33
    ,KRAKEN_WARRIOR = 34
    ,SHARK_BAIT = 35
    ,SEAFOOD_SAMPLER = 36
    ,SEAFOOD_PLATTER = 37
    ,SEAFOOD_BUFFET = 38
    ,ULTIMATE_KRAKEN = 39
    ,TEST_ACHIEVEMENT = 40
    

}
