using UnityEngine;
public enum BattleBonusType
{
    // Fields
    MORE_RAINBOW = 0
    ,LESS_RAINBOW = 1
    ,LONGER_STUN = 2
    ,SHORTER_STUN = 3
    ,RIGHT_BUBBLE = 4
    ,WRONG_BUBBLE = 5
    ,WIN_MORE_BP = 6
    ,LOSE_LESS_BP = 7
    ,FASTER_SUPER = 8
    ,SLOWER_SUPER = 9
    ,LESS_STUN_BREAKER_COST = 10
    ,MORE_STUN_BREAKER_COST = 11
    ,WIN_MORE_PRIZE = 12
    ,LOSE_LESS_WAGER = 13
    ,DOUBLE_PRIZE = 14
    ,WAGER_PROTECTION = 15
    ,ENHANCER_DISCOUNT = 16
    ,AMPLIFIER_DISCOUNT = 17
    ,NA = 999
    

}
