using UnityEngine;
public enum FontSubStyle
{
    // Fields
    NONE = 0
    ,XXXXEXO_PLAIN = 1
    ,BOLD_D1 = 2
    ,BOLD_BLACK_LINE_D2O2 = 3
    ,XXXXXADUMU = 4
    ,BOLD_WHITE_LINE_D2O2 = 5
    ,XXXXXEXO_BOLD_SHADOW = 6
    ,XXXXXXXXXADUMU_BLACK_OUTLINE = 7
    ,XXXXXXXXXXEXO_BOLD_BLACK_OUTLINE_THICK = 8
    ,BOLD_BLUE_LINE_D4O3 = 9
    ,XXXXXXEXO_ITALIC_TITLE = 10
    ,IKA_RED_LINE_O2 = 11
    ,TAKO_BLUE_LINE_O2 = 12
    ,CELEB_PURPLE_LINE_O2 = 13
    ,SPEC_ORANGE_LINE_O2 = 14
    ,SPEC_TEAL_LINE_O2 = 15
    ,XXXXXXSHADOW_WITH_BLACK_OUTLINE = 16
    ,EARTH_YELLOW_LINE_O2 = 17
    ,DARK_PURPLE_LINE_O2 = 18
    ,DARK_GREEN_LINE_O2 = 19
    ,BOLD_GRAY_LINE_D2O2 = 20
    ,WHITE_LINE_O2 = 21
    ,GREEN_LINE_O2 = 22
    ,RED_LINE_O2 = 23
    ,GREEN_LINE_D2O4 = 24
    ,YELLOW_LINE = 25
    

}
